// <auto-generated />
namespace WebApp_AAJI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class kategory_cuti : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kategory_cuti));
        
        string IMigrationMetadata.Id
        {
            get { return "201511170638001_kategory_cuti"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
